// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOfGOjdpVQZtnhwTjmNRy8mApY993zHfc',
    appId: '1:314090361026:web:50d629657a34fac2632b5b',
    messagingSenderId: '314090361026',
    projectId: 'smart-industry-panels',
    authDomain: 'smart-industry-panels.firebaseapp.com',
    storageBucket: 'smart-industry-panels.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPwTMv1WqlaoxSyaLRLmFBRNrjeavOUmM',
    appId: '1:314090361026:android:20ff9bc57650ec71632b5b',
    messagingSenderId: '314090361026',
    projectId: 'smart-industry-panels',
    storageBucket: 'smart-industry-panels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANDwRsSjr959L4LYD91P_ANiK5ThsVz-s',
    appId: '1:314090361026:ios:4caed628c2c7df8d632b5b',
    messagingSenderId: '314090361026',
    projectId: 'smart-industry-panels',
    storageBucket: 'smart-industry-panels.appspot.com',
    iosClientId: '314090361026-dk7oi1b5olvlhfvs4cu6brcd41s5svpq.apps.googleusercontent.com',
    iosBundleId: 'com.smartindustry.app',
  );
}
